branch/urls.py
from django.urls import path
from . import views
from . views import (BranchCreateView, BranchDetailView,
                     BranchEditView, BranchListView)

app_name = 'branch'

urlpatterns = [
    path('branch/', BranchListView.as_view(), name='branch_list'),
    path('branch/create/', BranchCreateView.as_view(), name='create_branch'),
    path('branch/detail/<int:pk>/',
         BranchDetailView.as_view(), name='branch_detail'),
    path('branch/edit/<int:pk>/',
         BranchEditView.as_view(), name='edit_branch'),
    path('branch/inactive/<int:pk>/',
         views.delete_branch, name='delete_branch'),
]

clients/urls.py
from django.urls import path
from . import views
from . views import (ClientListView, ClientCreateView,
                     ClientEditView, ClientDetailView)

app_name = 'clients'
urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/new/',
         ClientCreateView.as_view(), name='create_client'),
    path('clients/update/<int:pk>/',
         ClientEditView.as_view(), name='edit_client'),
    path('clients/detail/<int:pk>/',
         ClientDetailView.as_view(), name='client_detail'),
    path('clients/inactive/<int:pk>/',
         views.delete_client, name='delete_client'),
    # path('clients/permanent/delete/<int:pk>/',
    #      views.permanent_delete, name='permanent_delete'),
    path('deposits/', views.deposit_view, name='deposits'),
    path('withdrawals', views.withdrawal_view, name='withdrawals'),
    path('transaction_view/', views.transaction_view, name='transaction_view'),
    path('deposit/receipt/<int:pk>/', views.print_client_deposit,
         name='print_client_deposit'),
    path('withdrawal/receipt/<int:pk>/', views.print_client_withdrawal,
         name='print_client_withdrawal'),
]

mboapa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, re_path
#from django.conf.urls import url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dashboard.urls')),
    path('branch/', include('branch.urls')),
    path('clients/', include('clients.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

clients/forms.py
from django import forms
# import datetime
from . models import Deposit, Withdrawal


class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = ['client', 'amount']


class WithdrawalForm(forms.ModelForm):
    class Meta:
        model = Withdrawal
        fields = ['client', 'amount']

    # def __init__(self, *args, **kwargs):
    #     self.client = kwargs.pop('client', None)
    #     super(WithdrawalForm, self).__init__(*args, **kwargs)

    # def clean_amount(self):
    #     amount = self.cleaned_data['amount']
    #     if self.client.account_balance < amount:
    #         raise forms.ValidationError(
    #             'Client Can Not Withdraw More Than Balance.')
    #     return amount

clients/views.py
from django.utils import timezone

from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404, HttpResponse

from dashboard.models import User
from django.db.models import Sum

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.admin.views.decorators import staff_member_required

from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView, DetailView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.messages.views import SuccessMessageMixin

from . models import Client, Deposit, Withdrawal
from . forms import DepositForm, WithdrawalForm
from dashboard.decorators import manager_required, teller_required


#========================================================================================#
#                                   Handling Client views                                #
#========================================================================================#

class ClientListView(LoginRequiredMixin, ListView):
    template_name = 'client/list_form.html'

    model = Client
    field_list = ['id', 'account_name', 'account_number',
                  'account_balance', 'gender', 'account_photo', 'is_active', 'created_on']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel_name'] = 'Client Lists'
        context['panel_title'] = 'Client List'
        return context


@method_decorator([login_required, manager_required], name='dispatch')
class ClientCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'client/creation_form.html'

    model = Client
    success_message = 'Successfully created client'
    fields = ['name', 'mandate', 'account_purpose', 'is_saving_account', 'is_current_account',
              'is_active', 'account_photo', 'account_balance', 'marital_status', 'gender', 'place_of_birth', 'date_of_birth', 'nationality',
              'hometown', 'region_or_state', 'mother_name', 'father_name', 'occupation', 'ssnit_number', 'tin_number', 'residential_address', 'residential_city',
              'residential_region', 'residential_phone', 'residential_status', 'national_identity', 'id_number', 'id_issue_date', 'id_expiry_date',
              'country_of_issue', 'email', 'employment_type', 'city_of_employment', 'region_of_employment', 'nature_of_business', 'nxt_of_kin_name',
              'nxt_of_kin_contact', 'relation_with_kin', 'nxt_of_kin_residence', 'nxt_of_kin_region', 'emergency_contact_name', 'emergency_contact_phone',
              'relation_with_emergency_contact', 'emergency_contact_residence', 'emergency_contact_region']


@method_decorator([login_required, manager_required], name='dispatch')
class ClientEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'client/update_form.html'

    model = Client
    success_message = 'Successfully updated client'
    fields = ['name', 'mandate', 'account_purpose', 'is_saving_account', 'is_current_account',
              'is_active', 'account_photo', 'account_balance', 'marital_status', 'gender', 'place_of_birth', 'date_of_birth', 'nationality',
              'hometown', 'region_or_state', 'mother_name', 'father_name', 'occupation', 'ssnit_number', 'tin_number', 'residential_address', 'residential_city',
              'residential_region', 'residential_phone', 'residential_status', 'national_identity', 'id_number', 'id_issue_date', 'id_expiry_date',
              'country_of_issue', 'email', 'employment_type', 'city_of_employment', 'region_of_employment', 'nature_of_business', 'nxt_of_kin_name',
              'nxt_of_kin_contact', 'relation_with_kin', 'nxt_of_kin_residence', 'nxt_of_kin_region', 'emergency_contact_name', 'emergency_contact_phone',
              'relation_with_emergency_contact', 'emergency_contact_residence', 'emergency_contact_region']


class ClientDetailView(LoginRequiredMixin, DetailView):
    template_name = 'client/detail_form.html'
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel_name'] = 'Client Details'
        context['panel_title'] = 'Client Detail'
        return context


@staff_member_required
@login_required
@manager_required
def delete_client(request, pk):
    if request.user.is_staff:
        client = get_object_or_404(Client, id=pk)
        if client.is_active:
            client.is_active = False
        else:
            client.is_active = True
        client.save()
        messages.success(
            request, 'Client is now dormant!')
    return HttpResponseRedirect(reverse('clients:client_list'))


# @staff_member_required
# @login_required
# @manager_required
# # @permission_required('clients.permanent_delete', login_url='/accounts/login/', raise_exception=True)
# def permanent_delete(request, pk):
#     '''Permanently delete client'''
#     if request.user.is_staff:
#         client = get_object_or_404(Client, id=pk)
#         if client.is_closed_account and timezone.now().month:
#             client.is_closed_account = False
#         else:
#             client.is_closed_account = True
#         client.delete()
#         messages.success(request, "Permanently deleted client in a month time")
#         return HttpResponseRedirect(reverse('clients:client_list'))


#===================================================================================================#
#                   Handling Transactions(Deposits & Withdrawals) Views                             #
#===================================================================================================#

@login_required
def deposit_view(request):
    form = DepositForm(request.POST or None)

    if form.is_valid():
        deposit = form.save(commit=False)
        deposit.save()
        deposit.client.account_number = deposit.client.account_number
        # adds client deposit to balance
        deposit.client.account_balance += deposit.amount
        deposit.client.save()
        messages.success(
            request, 'Client Have Deposited {} GHc.'.format(deposit.amount))
        return redirect('clients:transaction_view')
    context = {'title': 'Deposit', 'form': form}
    return render(request, 'transactions/deposit.html', context)


@login_required
def withdrawal_view(request):
    form = WithdrawalForm(request.POST or None)

    if form.is_valid():
        withdrawal = form.save(commit=False)
        if withdrawal.client.account_balance >= withdrawal.amount:
            # subtracts client withdrawal from balance
            withdrawal.client.account_balance -= withdrawal.amount
            withdrawal.client.save()
            withdrawal.save()
            messages.success(
                request, 'Client have Withdrawn {} GHc.'.format(withdrawal.amount))
            return redirect('clients:transaction_view')
        else:
            messages.info(
                request, 'Client Can Not Withdraw More Than Balance. Please Return To Previous Page')
    context = {'title': 'Withdraw', 'form': form}
    return render(request, 'transactions/withdraw.html', context)


@login_required
# @permission_required('clients.transaction_view', login_url='/accounts/login/', raise_exception=True)
def transaction_view(request):
    deposits = Deposit.objects.all()
    withdrawals = Withdrawal.objects.all()
    total_deposits = Deposit.objects.filter(transaction_time__gte=timezone.now().replace(
        month=1, hour=0, minute=0, second=0, microsecond=0)).aggregate(amount__sum=Sum('amount'))['amount__sum']
    total_withdrawals = Withdrawal.objects.filter(transaction_time__gte=timezone.now().replace(
        month=1, hour=0, minute=0, second=0, microsecond=0)).aggregate(amount__sum=Sum('amount'))['amount__sum']
    context = {
        'deposits': deposits,
        'withdrawals': withdrawals,
        'total_deposits': total_deposits,
        'total_withdrawals': total_withdrawals
    }
    return render(request, 'transactions/list_form.html', context)


@login_required
def print_client_deposit(request, pk):
    deposits = get_object_or_404(Deposit, id=pk)
    context = {'deposits': deposits}
    return render(request, 'transactions/client_depostit.html', context)


@login_required
def print_client_withdrawal(request, pk):
    withdrawal = get_object_or_404(Withdrawal, id=pk)
    context = {'withdrawal': withdrawal}
    return render(request, 'transactions/client_withdrawal.html', context)

clients/templates/client/creation_form.html
{% extends 'base_generic.html' %}

{% load static %}
{% load i18n %}

{% load bootstrap3 %}


{% block content %}
	<div class="block block-condensed">
	    <div class="app-heading app-heading-small">                                        
	        <div class="title">
	            <h2>New Client</h2>
	            <p>Handles the creation of new clients.</p>
	        </div>
	    </div>
	    <div class="block-content">
		    <form action="" method='POST' role='form' class="form" enctype="multipart/form-data" {% if layout != 'vertical' %}class="form-{{ layout }}"{% endif %}>
				{% csrf_token %}
				{% bootstrap_form form %}
				{% bootstrap_form_errors form %}
		        <input type="submit" name="submit" value="Submit" class="btn btn-primary btn-clean btn-lg btn-rounded">
			</form>
	    </div>
	</div>

{% endblock %}
{% block script_js %}
<script type="text/javascript">
	var selector = document.getElementById("id_account_photo");
	selector.setAttribute("class", "file-input btn btn-primary");
</script>
{% endblock %}

clients/templates/client/detail_form.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-12 col-xs-12">                                
        <div class="block block-condensed padding-top-20">
            <div class="contact contact-container contact-single">
            	{% if object.account_photo.url%}
	                <img src="{{ object.account_photo.url }}" alt="{{ object.account_name }}" style="width: 20%; height: 15%;">
                {% endif %}
                <div class="contact-container">
                    <a href="#">Account name: {{ object.account_name }}</a>
                    <span>Account number: {{ object.account_number }}</span>
                    <p>Account balance: GH₵{{ object.account_balance|floatformat:2 }}</p>
                </div>
            </div>
            <div class="col-md-3 col-xs-3">
            	<div class="list-group">
	            	<div style="font-size: 20px;"><span class="fa fa-angle-double-down"></span> General Information</div>                                       
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b> Mandate:</b> {{ object.mandate }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Account purpose:</b> {{ object.account_purpose }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Savings account?:</b> {{ object.is_saving_account }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Current account?:</b> {{ object.is_current_account }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Active account?:</b> {{ object.is_active }}</div>                                                                                                                                                                  
	            </div>
            </div>     
            <div class="col-md-3 col-xs-3">
            	<div class="list-group">
	            	<div style="font-size: 20px;"><span class="fa fa-angle-double-down"></span> Personal Information</div>    
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Full Name:</b> {{ object.name }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Marital Status:</b> {{ object.marital_status }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Gender:</b> {{ object.gender }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Place of birth:</b> {{ object.place_of_birth }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Date of birth:</b> {{ object.date_of_birth }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Nationality:</b> {{ object.nationality }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Hometown:</b> {{ object.hometown }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Region / State:</b> {{ object.region_or_state }}</div>  
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Mother's name:</b> {{ object.mother_name }}</div>   
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Father's name:</b> {{ object.father_name }}</div> 
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>Occupation:</b> {{ object.occupation }}</div> 
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>SSNIT number:</b> {{ object.ssnit_number }}</div>   
	                <div class="list-group-item"><span class="fa fa-angle-right"></span><b>TIN number:</b> {{ object.tin_number }}</div>                                     
	            </div>
            </div>
            <div class="col-md-3 col-xs-3">
            	<div class="list-group">
            		<div style="font-size: 20px;"><span class="fa fa-angle-double-down"></span> Contact Information</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Residential address:</b> {{ object.residential_address }}</div> 
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Residential Town:</b> {{ object.residential_city }}</div> 
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Residential Region:</b> {{ object.residential_region }}</div> 
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Residential mobile #:</b> {{ object.residential_phone }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Residential status:</b> {{ object.residential_status }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>National identity:</b> {{ object.national_identity }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>National identity #:</b> {{ object.id_number }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>ID issued date:</b> {{ object.id_issue_date }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>ID expiry date:</b> {{ object.id_expiry_date }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Country ID was issued:</b> {{ object.country_of_issue }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Email address:</b> {{ object.email }}</div>
            	</div>
            </div>
            <div class="col-md-3 col-xs-3">
            	<div class="list-group">
            		<div style="font-size: 20px;"><span class="fa fa-angle-double-down"></span> Employment Information</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Employment type:</b> {{ object.employment_type }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>City/Town:</b> {{ object.city_of_employment }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Region:</b> {{ object.region_of_employment }}</div>
            		<div class="list-group-item"><<span class="fa fa-angle-right"></span><b>Nature of business:</b> {{ object.nature_of_business }}</div>
            	</div>
            </div>
            <div class="col-md-3 col-xs-3">
            	<div class="list-group">
            		<div style="font-size: 20px;"><span class="fa fa-angle-double-down"></span> Kin Information</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Kin name:</b> {{ object.nxt_of_kin_name }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Kin contact:</b> {{ object.nxt_of_kin_contact }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Relation:</b> {{ object.relation_with_kin }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Residence:</b> {{ object.nxt_of_kin_residence }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Region:</b> {{ object.nxt_of_kin_region }}</div>
            	</div>
            </div>
            <div class="col-md-3 col-xs-3">
            	<div class="list-group">
            		<div style="font-size: 20px;"><span class="fa fa-angle-double-down"></span> Emergency Contact</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Contact name:</b> {{ object.emergency_contact_name }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Contact phone:</b> {{ object.emergency_contact_phone}}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Relation:</b> {{ object.relation_with_emergency_contact }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Residence:</b> {{ object.emergency_contact_residence }}</div>
            		<div class="list-group-item"><span class="fa fa-angle-right"></span><b>Region:</b> {{ object.emergency_contact_region }}</div>
            	</div>
            </div>
            <div class="block-content padding-top-20">
                <div class="row">
                    <div class="col-md-6">
                        <a class="btn btn-info btn-clean btn-block" href="{% url 'clients:edit_client' object.pk %}">Update Client</a>
                    </div>
                    <div class="col-md-6">
                        <a class="btn btn-danger btn-clean btn-block" data-toggle="modal" data-target="#modal-small">Make Client Inactive</a>
                    </div>
                </div>                                        
            </div>
        </div>                                
    </div>
</div>

<!-- MODAL SMALL -->
<div class="modal fade" id="modal-small" tabindex="-1" role="dialog" aria-labelledby="modal-small-header">                        
    <div class="modal-dialog modal-sm modal-danger" role="document">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" class="icon-cross"></span></button>

        <div class="modal-content">
            <div class="modal-header">                        
                <h4 class="modal-title" id="modal-small-header">Delete Client</h4>
            </div>
            <div class="modal-body">
                <h2 align="center">Confirm client as inactive?</h2>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                <a type="button" class="btn btn-danger" href="{% url 'clients:delete_client' object.pk %}">Submit</a>
            </div>
        </div>
    </div>            
</div>
<!-- END MODAL SMALL -->
{% endblock %}

clients/templates/client/list_form.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}
<!-- NEW DEPOSITS -->                        
<div class="row">
    <div class="col-md-4">
        <div class="tile-basic tile-basic-icon-top">
            <div class="tile-icon">
                <span class="icon-cash-dollar"></span>
            </div>
            <div class="tile-content text-center">
                <h3 class="tile-title">Deposits</h3>
                <p>Manages all Deposits. User can manage clients deposits by selecting the specific client from this very page or manager.</p>
                <a href="{% url 'clients:deposits' %}" class="btn btn-primary btn-clean">Make Deposit</a>
            </div>
        </div>                                
    </div>
    <div class="col-md-4">
        <div class="tile-basic tile-basic-icon-top">
            <div class="tile-icon">
                <span class="icon-receipt"></span>
            </div>
            <div class="tile-content text-center">
                <h3 class="tile-title">Withdrawals</h3>
                <p>Manages all withdrawal. User can manage clients withdrawals by selecting the specific client from this very page or manager.</p>
                <a href="{% url 'clients:withdrawals' %}" class="btn btn-primary btn-clean">Make Withdrawal</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="tile-basic tile-basic-icon-top">
            <div class="tile-icon">
                <span class="icon-apartment"></span>
            </div>
            <div class="tile-content text-center">
                <h3 class="tile-title">Bank Branch</h3>
                <p>Manages all bank branches. From creation of a new bank branch to and viewing its performance. This page is for administrators only.</p>
                <a href="{% url 'branch:branch_list' %}" class="btn btn-primary btn-clean">Contact Manager</a>
            </div>
        </div>
    </div>                            
</div>                                                
<!-- END NEW DEPOSITS -->

<!-- DEPOSITS -->
<div class="block block-condensed">
    <div class="app-heading app-heading-small">                                        
        <div class="title">
            <h2>My Clients</h2>
            <p>List of your active and inactive clients</p>
        </div>
        <div class="heading-elements">                                    
            <div class="heading-elements">
                <a class="btn btn-primary btn-icon-fixed" href="{% url 'clients:create_client' %}"><span class="icon-user-plus"></span> Add New Client</a>
            </div>
        </div>
    </div>
    
    <div class="block-content">
        <table class="table table-striped table-bordered datatable-extended">
            <thead>
                <tr>
                    <th>#</th>
                    <th style="width: 25%;">Account Name</th>
                    <th style="width: 35%;">Account Number</th>
                    <th>Account Balance</th>
                    <th style="width: 10%;">Gender</th>
                    <th style="width: 10%;">Photo</th>
                    <th>Active?</th>
                    <th style="width: 20%;">Actions</th>
                </tr>
            </thead>
            <tbody>
            	{% for client in object_list %}
                <tr>
                    <td>{{ client.id }}</td>
                    <td><strong>{{ client.account_name }}</strong> <span class="fa fa-long-arrow-right"></span> {{ client.created_on }}</td>
                    <td><strong>{{ client.account_number }}</strong></td>
                    <td>GH₵ {{ client.account_balance|floatformat:2 }}</td>
                    <td>{{ client.gender }}</td>
                    {% if client.account_photo %}
                        <td>
                            <img src="{{ client.account_photo.url }}" class="contact" style="align-items: center;">
                        </td>
                    {% else %}
                        <img src="{% static 'img/user/no-image.png' %}" alt="{{ client.account_name }}">
                    {% endif %}
                    {% if client.is_active is True %}
                        <td><span class="label label-success label-bordered">{{ client.is_active }}</span></td>
                    {% else %}
                    	<td><span class="label label-danger label-bordered">{{ client.is_active }}</span></td>
                    {% endif %}
                    <td>
                        <a class="btn btn-warning btn-icon btn-clean" href="{% url 'clients:client_detail' client.pk %}"><span class="icon-document"></span></a>
                        {% if user.is_manager %}
	                        <a class="btn btn-danger btn-icon btn-clean" href="{% url 'clients:delete_client' client.pk %}"><span class="icon-recycle"></span></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}                                                                       
            </tbody>
        </table>
    </div>
</div>
<!-- END DEPOSITS -->


{% endblock %}

clients/templates/client/update_form.html
{% extends 'base_generic.html' %}

{% load static %}
{% load i18n %}

{% load bootstrap3 %}

{% block content %}
	<div class="block block-condensed">
	    <div class="app-heading app-heading-small">                                        
	        <div class="title">
	            <h2>Update Client Record</h2>
	            <p>Handles the modification of existing clients.</p>
	        </div>
	    </div>
	    <div class="block-content">
		    <form action="{% url 'clients:edit_client' object.pk %}" method='POST' role='form' class="form" enctype="multipart/form-data" {% if layout != 'vertical' %}class="form-{{ layout }}"{% endif %}>
				{% csrf_token %}
				{% bootstrap_form form %}
				{% bootstrap_form_errors form %}
		        <input type="submit" name="submit" value="Submit" class="btn btn-primary btn-clean btn-lg btn-rounded">
			</form>
	    </div>
	</div>
{% endblock %}

{% block script_js %}
<script type="text/javascript">
	var selector = document.getElementById("id_account_photo");
	selector.setAttribute("class", "file-input btn btn-primary");
</script>
{% endblock %}