branch/urls.py
from django.urls import path
from . import views
from . views import (BranchCreateView, BranchDetailView,
                     BranchEditView, BranchListView)

app_name = 'branch'

urlpatterns = [
    path('branch/', BranchListView.as_view(), name='branch_list'),
    path('branch/create/', BranchCreateView.as_view(), name='create_branch'),
    path('branch/detail/<int:pk>/',
         BranchDetailView.as_view(), name='branch_detail'),
    path('branch/edit/<int:pk>/',
         BranchEditView.as_view(), name='edit_branch'),
    path('branch/inactive/<int:pk>/',
         views.delete_branch, name='delete_branch'),
]

clients/urls.py
from django.urls import path
from . import views
from . views import (ClientListView, ClientCreateView,
                     ClientEditView, ClientDetailView)

app_name = 'clients'
urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/new/',
         ClientCreateView.as_view(), name='create_client'),
    path('clients/update/<int:pk>/',
         ClientEditView.as_view(), name='edit_client'),
    path('clients/detail/<int:pk>/',
         ClientDetailView.as_view(), name='client_detail'),
    path('clients/inactive/<int:pk>/',
         views.delete_client, name='delete_client'),
    # path('clients/permanent/delete/<int:pk>/',
    #      views.permanent_delete, name='permanent_delete'),
    path('deposits/', views.deposit_view, name='deposits'),
    path('withdrawals', views.withdrawal_view, name='withdrawals'),
    path('transaction_view/', views.transaction_view, name='transaction_view'),
    path('deposit/receipt/<int:pk>/', views.print_client_deposit,
         name='print_client_deposit'),
    path('withdrawal/receipt/<int:pk>/', views.print_client_withdrawal,
         name='print_client_withdrawal'),
]

mboapa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, re_path
#from django.conf.urls import url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dashboard.urls')),
    path('branch/', include('branch.urls')),
    path('clients/', include('clients.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

clients/forms.py
from django import forms
# import datetime
from . models import Deposit, Withdrawal


class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = ['client', 'amount']


class WithdrawalForm(forms.ModelForm):
    class Meta:
        model = Withdrawal
        fields = ['client', 'amount']

    # def __init__(self, *args, **kwargs):
    #     self.client = kwargs.pop('client', None)
    #     super(WithdrawalForm, self).__init__(*args, **kwargs)

    # def clean_amount(self):
    #     amount = self.cleaned_data['amount']
    #     if self.client.account_balance < amount:
    #         raise forms.ValidationError(
    #             'Client Can Not Withdraw More Than Balance.')
    #     return amount

clients/views.py
from django.utils import timezone

from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404, HttpResponse

from dashboard.models import User
from django.db.models import Sum

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.admin.views.decorators import staff_member_required

from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView, DetailView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.messages.views import SuccessMessageMixin

from . models import Client, Deposit, Withdrawal
from . forms import DepositForm, WithdrawalForm
from dashboard.decorators import manager_required, teller_required


#========================================================================================#
#                                   Handling Client views                                #
#========================================================================================#

class ClientListView(LoginRequiredMixin, ListView):
    template_name = 'client/list_form.html'

    model = Client
    field_list = ['id', 'account_name', 'account_number',
                  'account_balance', 'gender', 'account_photo', 'is_active', 'created_on']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel_name'] = 'Client Lists'
        context['panel_title'] = 'Client List'
        return context


@method_decorator([login_required, manager_required], name='dispatch')
class ClientCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'client/creation_form.html'

    model = Client
    success_message = 'Successfully created client'
    fields = ['name', 'mandate', 'account_purpose', 'is_saving_account', 'is_current_account',
              'is_active', 'account_photo', 'account_balance', 'marital_status', 'gender', 'place_of_birth', 'date_of_birth', 'nationality',
              'hometown', 'region_or_state', 'mother_name', 'father_name', 'occupation', 'ssnit_number', 'tin_number', 'residential_address', 'residential_city',
              'residential_region', 'residential_phone', 'residential_status', 'national_identity', 'id_number', 'id_issue_date', 'id_expiry_date',
              'country_of_issue', 'email', 'employment_type', 'city_of_employment', 'region_of_employment', 'nature_of_business', 'nxt_of_kin_name',
              'nxt_of_kin_contact', 'relation_with_kin', 'nxt_of_kin_residence', 'nxt_of_kin_region', 'emergency_contact_name', 'emergency_contact_phone',
              'relation_with_emergency_contact', 'emergency_contact_residence', 'emergency_contact_region']


@method_decorator([login_required, manager_required], name='dispatch')
class ClientEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'client/update_form.html'

    model = Client
    success_message = 'Successfully updated client'
    fields = ['name', 'mandate', 'account_purpose', 'is_saving_account', 'is_current_account',
              'is_active', 'account_photo', 'account_balance', 'marital_status', 'gender', 'place_of_birth', 'date_of_birth', 'nationality',
              'hometown', 'region_or_state', 'mother_name', 'father_name', 'occupation', 'ssnit_number', 'tin_number', 'residential_address', 'residential_city',
              'residential_region', 'residential_phone', 'residential_status', 'national_identity', 'id_number', 'id_issue_date', 'id_expiry_date',
              'country_of_issue', 'email', 'employment_type', 'city_of_employment', 'region_of_employment', 'nature_of_business', 'nxt_of_kin_name',
              'nxt_of_kin_contact', 'relation_with_kin', 'nxt_of_kin_residence', 'nxt_of_kin_region', 'emergency_contact_name', 'emergency_contact_phone',
              'relation_with_emergency_contact', 'emergency_contact_residence', 'emergency_contact_region']


class ClientDetailView(LoginRequiredMixin, DetailView):
    template_name = 'client/detail_form.html'
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel_name'] = 'Client Details'
        context['panel_title'] = 'Client Detail'
        return context


@staff_member_required
@login_required
@manager_required
def delete_client(request, pk):
    if request.user.is_staff:
        client = get_object_or_404(Client, id=pk)
        if client.is_active:
            client.is_active = False
        else:
            client.is_active = True
        client.save()
        messages.success(
            request, 'Client is now dormant!')
    return HttpResponseRedirect(reverse('clients:client_list'))


# @staff_member_required
# @login_required
# @manager_required
# # @permission_required('clients.permanent_delete', login_url='/accounts/login/', raise_exception=True)
# def permanent_delete(request, pk):
#     '''Permanently delete client'''
#     if request.user.is_staff:
#         client = get_object_or_404(Client, id=pk)
#         if client.is_closed_account and timezone.now().month:
#             client.is_closed_account = False
#         else:
#             client.is_closed_account = True
#         client.delete()
#         messages.success(request, "Permanently deleted client in a month time")
#         return HttpResponseRedirect(reverse('clients:client_list'))


#===================================================================================================#
#                   Handling Transactions(Deposits & Withdrawals) Views                             #
#===================================================================================================#

@login_required
def deposit_view(request):
    form = DepositForm(request.POST or None)

    if form.is_valid():
        deposit = form.save(commit=False)
        deposit.save()
        deposit.client.account_number = deposit.client.account_number
        # adds client deposit to balance
        deposit.client.account_balance += deposit.amount
        deposit.client.save()
        messages.success(
            request, 'Client Have Deposited {} GHc.'.format(deposit.amount))
        return redirect('clients:transaction_view')
    context = {'title': 'Deposit', 'form': form}
    return render(request, 'transactions/deposit.html', context)


@login_required
def withdrawal_view(request):
    form = WithdrawalForm(request.POST or None)

    if form.is_valid():
        withdrawal = form.save(commit=False)
        if withdrawal.client.account_balance >= withdrawal.amount:
            # subtracts client withdrawal from balance
            withdrawal.client.account_balance -= withdrawal.amount
            withdrawal.client.save()
            withdrawal.save()
            messages.success(
                request, 'Client have Withdrawn {} GHc.'.format(withdrawal.amount))
            return redirect('clients:transaction_view')
        else:
            messages.info(
                request, 'Client Can Not Withdraw More Than Balance. Please Return To Previous Page')
    context = {'title': 'Withdraw', 'form': form}
    return render(request, 'transactions/withdraw.html', context)


@login_required
# @permission_required('clients.transaction_view', login_url='/accounts/login/', raise_exception=True)
def transaction_view(request):
    deposits = Deposit.objects.all()
    withdrawals = Withdrawal.objects.all()
    total_deposits = Deposit.objects.filter(transaction_time__gte=timezone.now().replace(
        month=1, hour=0, minute=0, second=0, microsecond=0)).aggregate(amount__sum=Sum('amount'))['amount__sum']
    total_withdrawals = Withdrawal.objects.filter(transaction_time__gte=timezone.now().replace(
        month=1, hour=0, minute=0, second=0, microsecond=0)).aggregate(amount__sum=Sum('amount'))['amount__sum']
    context = {
        'deposits': deposits,
        'withdrawals': withdrawals,
        'total_deposits': total_deposits,
        'total_withdrawals': total_withdrawals
    }
    return render(request, 'transactions/list_form.html', context)


@login_required
def print_client_deposit(request, pk):
    deposits = get_object_or_404(Deposit, id=pk)
    context = {'deposits': deposits}
    return render(request, 'transactions/client_depostit.html', context)


@login_required
def print_client_withdrawal(request, pk):
    withdrawal = get_object_or_404(Withdrawal, id=pk)
    context = {'withdrawal': withdrawal}
    return render(request, 'transactions/client_withdrawal.html', context)

clients/templates/transactions/client_depostit.html
{% extends 'base_generic.html' %}

{% load static %}

{% block static_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}">
{% endblock %}

{% block content %}
<!-- START PAGE CONTAINER -->
<div class="container container-boxed" id=printarea>
    
    <div class="row">                            
        <div class="col-md-12 tble">
            
            <!-- RECENT ACTIVITY -->
            <div class="block block-condensed">
                <div class="app-heading app-heading-small">
                    <div class="title">
                        <h2>Mboa Pa Financial Service</h2>
                    </div>
                    <div class="heading-elements">
                        <button class="btn btn-success btn-clean btn-icon" onclick="PrintPreview()"><span class="icon-printer"></span></button>
                    </div>
                </div>
				<div class="block-content">
                    <div class="listing margin-bottom-0">                                                                                
                        <div class="listing-item listing-item-with-icon">
                            <img src="{% static 'img/bankLOGO.jpg' %}" width="60px" height="60px">                                                
                            <h4 class="text-rg text-bold">Transaction Receipt - Cash Deposit Slip <span class="text-muted pull-right">{{ deposits.transaction_time }}</span></h4>                                                
                            <div class="list-group list-group-inline">
                            	<div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Teller Name</span><br>
                                    <span class="text-bold">{{ deposits.client.user }}</span>
                                </div>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Document Number</span><br>
                                    <span class="text-bold">{{ deposits.id }}</span>
                                </div>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Account Name</span><br>
                                    <span class="text-bold">{{ deposits.client.account_name }}</span>
                                </div>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Account Number</span><br>
                                    <span class="text-bold">{{ deposits.client.account_number }}</span>
                                </div><hr>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Amount</span><br>
                                    <span class="text-bold text-danger">GH₵ {{ deposits.amount }}</span>
                                </div>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Balance</span><br>
                                    <span class="text-bold">GH₵ {{ deposits.client.account_balance }}</span>
                                </div>                                                    
                            </div>                                                
                        </div>
                    </div>
                    <div class="block-divider-text">{{ deposits.transaction_time }}</div>
                </div>
            </div>
        </div>
    </div>
</div> 
{% endblock %}

{% block script_js %}
<script type="text/javascript">
	function PrintPreview(){
		var toPrint = document.getElementById('printarea');
		var popupWin = window.print();
		popupWin.document.open();
		popupWin.document.write('<html><title>::Print Preview::</title><link rel="stylesheet" type="text/css" href="print.css" media="screen"/></head><body">');
		popupWin.document.write(toPrint.innerHTML);
		popupWin.document.write('</html>');
		popupWin.document.close();
	}
</script>
{% endblock %}

clients/templates/transactions/client_withdrawal.html
{% extends 'base_generic.html' %}

{% load static %}

{% block static_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}">
{% endblock %}

{% block content %}
<!-- START PAGE CONTAINER -->
<div class="container container-boxed" id=printarea>
    
    <div class="row">                            
        <div class="col-md-12 tble">
            
            <!-- RECENT ACTIVITY -->
            <div class="block block-condensed">
                <div class="app-heading app-heading-small">
                    <div class="title">
                        <h2>Mboa Pa Financial Service</h2>
                    </div>
                    <div class="heading-elements">
                        <button class="btn btn-success btn-clean btn-icon" onclick="PrintPreview()"><span class="icon-printer"></span></button>
                    </div>
                </div>
				<div class="block-content">
                    <div class="listing margin-bottom-0">                                                                                
                        <div class="listing-item listing-item-with-icon">
                            <img src="{% static 'img/bankLOGO.jpg' %}" width="60px" height="60px">                                                
                            <h4 class="text-rg text-bold">Transaction Receipt - Cash Withdrawal Slip <span class="text-muted pull-right">{{ withdrawal.transaction_time }}</span></h4>                                                
                            <div class="list-group list-group-inline">
                            	<div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Teller Name</span><br>
                                    <span class="text-bold">{{ withdrawal.client.user }}</span>
                                </div>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Document Number</span><br>
                                    <span class="text-bold">{{ withdrawal.id }}</span>
                                </div>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Account Name</span><br>
                                    <span class="text-bold">{{ withdrawal.client.account_name }}</span>
                                </div>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Account Number</span><br>
                                    <span class="text-bold">{{ withdrawal.client.account_number }}</span>
                                </div><hr>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Amount</span><br>
                                    <span class="text-bold text-danger">GH₵ {{ withdrawal.amount }}</span>
                                </div>
                                <div class="list-group-item col-md-4 col-sm-4">
                                    <span class="text-muted">Balance</span><br>
                                    <span class="text-bold">GH₵ {{ withdrawal.client.account_balance }}</span>
                                </div>                                                    
                            </div>                                                
                        </div>
                    </div>
                    <div class="block-divider-text">{{ withdrawal.transaction_time }}</div>
                </div>
            </div>
        </div>
    </div>
</div> 
{% endblock %}

{% block script_js %}
<script type="text/javascript">
	function PrintPreview(){
		var toPrint = document.getElementById('printarea');
		var popupWin = window.print();
		popupWin.document.open();
		popupWin.document.write('<html><title>::Print Preview::</title><link rel="stylesheet" type="text/css" href="print.css" media="screen"/></head><body">');
		popupWin.document.write(toPrint.innerHTML);
		popupWin.document.write('</html>');
		popupWin.document.close();
	}
</script>
{% endblock %}

clients/templates/transactions/deposit.html
{% extends 'base_generic.html' %}

{% load static %}
{% load bootstrap3 %}

{% block content %}
<div class="block block-condensed">
    <div class="app-heading app-heading-small">                                        
        <div class="title">
            <h2>Deposits</h2>
            <p>Handles the creation of amount deposits.</p>
        </div>
    </div>
    <div class="block-content">
		<form method="post" action="" role='form' class="form" enctype="multipart/form-data" {% if layout != 'vertical' %}class="form-{{ layout }}"{% endif %}>
			{% csrf_token %}
			{% bootstrap_form form %}
			{% bootstrap_form_errors form %}
	        <input type="submit" name="submit" value="Submit" class="btn btn-primary btn-clean btn-block btn-rounded">
		</form>
	</div>
</div>

{% endblock %}
{% block script_js %}
<script type="text/javascript">
	var selector = document.getElementById("id_client");
	selector.setAttribute("data-live-search", "true");
	selector.setAttribute("class", "bs-select")
</script>
{% endblock %}

clients/templates/transactions/list_form.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}
<div class="block block-condensed">
    <div class="app-heading app-heading-small">                                        
        <div class="title">
            <blockquote><h1>Total Deposits | Total Withdrawal</h1>
            <h2>GH₵ {{ total_deposits|floatformat:2 }} | GH₵ {{ total_withdrawals|floatformat:2 }}</h2></blockquote>
        </div>
    </div>
</div>
<!-- DEPOSITS -->
<div class="block block-condensed">
    <div class="app-heading app-heading-small">                                        
        <div class="title">
            <h2>Deposits</h2>
            <p>All deposits</p>
        </div>
    </div>
    
    <div class="block-content">
        <table class="table table-striped table-bordered datatable-extended">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Client</th>
                    <th>Amount</th>
                    <th>Time</th>
                    <th>Reciepts</th>
                </tr>
            </thead>
            <tbody>
            	{% for deposit in deposits %}
                <tr>
                    <td>{{ deposit.id }}</td>
                    <td><strong>{{ deposit.client.account_name }}</td>
                    <td><strong>GH₵ {{ deposit.amount|floatformat:2}}</strong></td>
                    <td>{{ deposit.transaction_time }}</td>
                    <td>
                        <a href="{% url 'clients:print_client_deposit' deposit.pk %}" class="btn btn-primary btn-clean">Reciept</a>
                    </td>
                </tr>
                {% endfor %}                                                                     
            </tbody>
        </table>
    </div>
</div>
<!-- END DEPOSITS -->

<!-- WITHDRAWAL -->
<div class="block block-condensed">
    <div class="app-heading app-heading-small">                                        
        <div class="title">
            <h2>Withdrawal</h2>
            <p>All withdrawals</p>
        </div>
    </div>
    
    <div class="block-content">
        <table class="table table-striped table-bordered datatable-extended">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Client</th>
                    <th>Amount</th>
                    <th>Time</th>
                    <th>Reciepts</th>
                </tr>
            </thead>
            <tbody>
            	{% for withdraw in withdrawals %}
                <tr>
                    <td>{{ withdraw.id }}</td>
                    <td><strong>{{ withdraw.client.account_name }}</td>
                    <td><strong>GH₵ {{ withdraw.amount|floatformat:2}}</strong></td>
                    <td>{{ withdraw.transaction_time }}</td>
                    <td>
                        <a href="{% url 'clients:print_client_withdrawal' withdraw.pk %}" class="btn btn-primary btn-clean">Reciept</a>
                    </td>
                </tr>
                {% endfor %}                                                                     
            </tbody>
        </table>
    </div>
</div>
<!-- END WITHDRAWAL -->


{% endblock %}

clients/templates/transactions/withdraw.html
{% extends 'base_generic.html' %}

{% load static %}
{% load bootstrap3 %}

{% block content %}
<div class="block block-condensed">
    <div class="app-heading app-heading-small">                                        
        <div class="title">
            <h2>Withdrawals</h2>
            <p>Handles the creation of withdrawals.</p>
        </div>
    </div>
    <div class="block-content">
		<form method="post" action="" role='form' class="form" enctype="multipart/form-data" {% if layout != 'vertical' %}class="form-{{ layout }}"{% endif %}>
			{% csrf_token %}
			{% bootstrap_form form %}
			{% bootstrap_form_errors form %}
			<input type="submit" name="submit" value="Submit" class="btn btn-primary btn-clean btn-block btn-rounded">
		</form>
	</div>
</div>
{% endblock %}
{% block script_js %}
<script type="text/javascript">
	var selector = document.getElementById("id_client");
	selector.setAttribute("data-live-search", "true");
	selector.setAttribute("class", "bs-select")
</script>
{% endblock %}