branch/urls.py
from django.urls import path
from . import views
from . views import (BranchCreateView, BranchDetailView,
                     BranchEditView, BranchListView)

app_name = 'branch'

urlpatterns = [
    path('branch/', BranchListView.as_view(), name='branch_list'),
    path('branch/create/', BranchCreateView.as_view(), name='create_branch'),
    path('branch/detail/<int:pk>/',
         BranchDetailView.as_view(), name='branch_detail'),
    path('branch/edit/<int:pk>/',
         BranchEditView.as_view(), name='edit_branch'),
    path('branch/inactive/<int:pk>/',
         views.delete_branch, name='delete_branch'),
]

clients/urls.py
from django.urls import path
from . import views
from . views import (ClientListView, ClientCreateView,
                     ClientEditView, ClientDetailView)

app_name = 'clients'
urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/new/',
         ClientCreateView.as_view(), name='create_client'),
    path('clients/update/<int:pk>/',
         ClientEditView.as_view(), name='edit_client'),
    path('clients/detail/<int:pk>/',
         ClientDetailView.as_view(), name='client_detail'),
    path('clients/inactive/<int:pk>/',
         views.delete_client, name='delete_client'),
    # path('clients/permanent/delete/<int:pk>/',
    #      views.permanent_delete, name='permanent_delete'),
    path('deposits/', views.deposit_view, name='deposits'),
    path('withdrawals', views.withdrawal_view, name='withdrawals'),
    path('transaction_view/', views.transaction_view, name='transaction_view'),
    path('deposit/receipt/<int:pk>/', views.print_client_deposit,
         name='print_client_deposit'),
    path('withdrawal/receipt/<int:pk>/', views.print_client_withdrawal,
         name='print_client_withdrawal'),
]

mboapa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, re_path
#from django.conf.urls import url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dashboard.urls')),
    path('branch/', include('branch.urls')),
    path('clients/', include('clients.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

branch/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django.core.validators import RegexValidator

# phone validator using regular expressions
phone_regex = RegexValidator(
    regex=r'^\+?1?\d{9,15}$',
    message='Phone number invalid. Should start with example: +233'
)


class Branch(models.Model):
    ''' Manages bank branche information'''
    name = models.CharField(max_length=100, unique=True)
    opening_date = models.DateField()
    country = models.CharField(max_length=50)
    REGION = (
        ('Ashanti Region', 'Ashanti Region'),
        ('Bono Region', 'Bono Region'),
        ('Bono East', 'Bono East'),
        ('Ahafo Region', 'Ahafo Region'),
        ('Central Region', 'Central Region'),
        ('Eastern Region', 'Eastern Region'),
        ('Greater Accra', 'Greater Accra'),
        ('Northern Region', 'Northern Region'),
        ('Savannah Region', 'Savannah Region'),
        ('North East', 'North East'),
        ('Upper East', 'Upper East'),
        ('Upper West', 'Upper West'),
        ('Volta Region', 'Volta Region'),
        ('Oti Region', 'Oti Region'),
        ('Western Region', 'Western Region'),
        ('Western North', 'Western North'),
    )
    region = models.CharField(max_length=20, choices=REGION)
    city = models.CharField(max_length=100)
    phone_number = models.CharField(validators=[phone_regex], max_length=15)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('branch:branch_list')

    class Meta:
        verbose_name = 'Branch Name'
        verbose_name_plural = 'Branch Names'

branch/views.py
from django.shortcuts import reverse, get_object_or_404
from django.http import HttpResponseRedirect

from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView, DetailView

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from dashboard.decorators import manager_required
from django.contrib.messages.views import SuccessMessageMixin

from . models import Branch


@method_decorator([login_required, manager_required], name='dispatch')
class BranchCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'branch/creation_form.html'
    model = Branch
    success_message = 'Opened new branch'
    fields = ['name', 'opening_date', 'country',
              'region', 'city', 'phone_number']


@method_decorator([login_required, manager_required], name='dispatch')
class BranchListView(LoginRequiredMixin, ListView):
    template_name = 'branch/list_form.html'
    model = Branch
    field_list = ['name', 'opening_date',
                  'country', 'region', 'city', 'phone_number', 'is_active']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel_name'] = 'Bank Branches'
        context['panel_title'] = 'Bank Branch'
        return context


@method_decorator([login_required, manager_required], name='dispatch')
class BranchEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'branch/update_form.html'
    model = Branch
    success_message = 'Branch has been successfully updated'
    fields = ['name', 'opening_date', 'country',
              'region', 'city', 'phone_number', 'is_active']


@method_decorator([login_required, manager_required], name='dispatch')
class BranchDetailView(LoginRequiredMixin, DetailView):
    template_name = 'branch/detail_form.html'
    model = Branch

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel_name'] = 'Branch Details'
        context['panel_title'] = 'Branch Detail'
        return context


@staff_member_required
@login_required
@manager_required
def delete_branch(request, pk):
    if request.user.is_staff:
        branch = get_object_or_404(Branch, id=pk)
        if branch.is_active:
            branch.is_active = False
        else:
            branch.is_active = True
        branch.save()
    return HttpResponseRedirect(reverse('branch:branch_list'))

branch/templates/branch/creation_form.html
{% extends 'base_generic.html' %}

{% load static %}
{% load i18n %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
	<div class="block block-condensed">
	    <div class="app-heading app-heading-small">                                        
	        <div class="title">
	            <h2>New Branch</h2>
	            <p>Handles the creation of new bank branch.</p>
	        </div>
	    </div>
	    <div class="block-content">
		    <form action="" method='POST' role='form' class="form" enctype="multipart/form-data" {% if layout != 'vertical' %}class="form-{{ layout }}"{% endif %}>
				{% csrf_token %}
				{% bootstrap_form form %}
				{% bootstrap_form_errors form %}
		        <input type="submit" name="submit" value="Submit" class="btn btn-primary btn-clean btn-lg btn-rounded">
			</form>
	    </div>
	</div>
	{% include 'scripts_base.html' %}

{% endblock %}

branch/templates/branch/detail_form.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-12 col-xs-12">                                
        <div class="block block-condensed padding-top-20">
            <div class="contact contact-container contact-single">
	                <img src="{% static 'img/bankLOGO.jpg' %}" alt="{{ object.account_name }}" style="width: 20%; height: 15%;">
                <div class="contact-container">
                    <a href="#">Branch name: {{ object.name }}</a>
                    <span>Date Opened: {{ object.opening_date }}</span>
                    <p>Branch country: {{ object.country }}</p>
                </div>
                
            </div>
            <div class="col-md-12 col-xs-12">
            	<div class="list-group">
	            	<div style="font-size: 20px;"><span class="fa fa-angle-double-down"></span> Other Information</div>                                       
	                <div class="list-group-item"><span class="fa fa-angle-right"></span> Region: {{ object.region}}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span>City: {{ object.city }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span>Phone number: {{ object.phone_number }}</div>
	                <div class="list-group-item"><span class="fa fa-angle-right"></span>Active branch?: {{ object.is_active }}</div>      
	            </div>
            <div class="block-content padding-top-20">
                    <div class="row">
                        <div class="col-md-6">
                            <a class="btn btn-info btn-clean btn-block" href="{% url 'branch:edit_branch' object.pk %}">Update branch</a>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-danger btn-clean btn-block" data-toggle="modal" data-target="#modal-small">Make branch inactive</a>
                        </div>
                    </div>                                        
                </div>
            </div>     
        </div>                                
    </div>
</div>

<!-- MODAL SMALL -->
<div class="modal fade" id="modal-small" tabindex="-1" role="dialog" aria-labelledby="modal-small-header">                        
    <div class="modal-dialog modal-sm modal-danger" role="document">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" class="icon-cross"></span></button>

        <div class="modal-content">
            <div class="modal-header">                        
                <h4 class="modal-title" id="modal-small-header">Delete Branch</h4>
            </div>
            <div class="modal-body">
                <h2 align="center">Confirm branch as inactive?</h2>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                <a type="button" class="btn btn-danger" href="{% url 'branch:delete_branch' object.pk %}">Submit</a>
            </div>
        </div>
    </div>            
</div>
<!-- END MODAL SMALL -->
{% endblock %}

branch/templates/branch/list_form.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}
<!-- NEW DEPOSITS -->                        
<div class="row">
    <div class="col-md-4">
        <div class="tile-basic tile-basic-icon-top">
            <div class="tile-icon">
                <span class="icon-cash-dollar"></span>
            </div>
            <div class="tile-content text-center">
                <h3 class="tile-title">Deposits</h3>
                <p>Manages all Deposits. User can manage clients deposits by selecting the specific client from this very page or manager.</p>
                <a href="{% url 'clients:deposits' %}" class="btn btn-primary btn-clean">Make Deposit</a>
            </div>
        </div>                                
    </div>
    <div class="col-md-4">
        <div class="tile-basic tile-basic-icon-top">
            <div class="tile-icon">
                <span class="icon-receipt"></span>
            </div>
            <div class="tile-content text-center">
                <h3 class="tile-title">Withdrawals</h3>
                <p>Manages all withdrawal. User can manage clients withdrawals by selecting the specific client from this very page or manager.</p>
                <a href="{% url 'clients:withdrawals' %}" class="btn btn-primary btn-clean">Make Withdrawal</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="tile-basic tile-basic-icon-top">
            <div class="tile-icon">
                <span class="icon-apartment"></span>
            </div>
            <div class="tile-content text-center">
                <h3 class="tile-title">Bank Branch</h3>
                <p>Manages all bank branches. From creation of a new bank branch to and viewing its performance. This page is for administrators only.</p>
                <a href="{% url 'branch:branch_list' %}" class="btn btn-primary btn-clean">Contact Manager</a>
            </div>
        </div>
    </div>                            
</div>                                                
<!-- END NEW DEPOSITS -->

<!-- DEPOSITS -->
<div class="block block-condensed">
    <div class="app-heading app-heading-small">                                        
        <div class="title">
            <h2>{{ panel_name}}</h2>
            <p>{{ panel_title }}</p>
        </div>
        <div class="heading-elements">                                    
            <div class="heading-elements">
                <a class="btn btn-primary btn-icon-fixed" href="{% url 'branch:create_branch' %}"><span class="icon-city"></span> Add New Branch</a>
            </div>
        </div>
    </div>
    
    <div class="block-content">
        <table class="table table-striped table-bordered datatable-extended">
            <thead>
                <tr>
                    <th>#</th>
                    <th style="width: 25%;"> Name</th>
                    <th style="width: 35%;">Opening date</th>
                    <th>Country</th>
                    <th style="width: 10%;">Region</th>
                    <th style="width: 10%;">City</th>
                    <th>Phone number</th>
                    <th>Active?</th>
                    <th style="width: 20%;">Actions</th>
                </tr>
            </thead>
            <tbody>
            	{% for branch in object_list %}
                <tr>
                    <td>{{ branch.id }}</td>
                    <td><strong>{{ branch.name }}</td>
                    <td><strong>{{ branch.opening_date }}</strong></td>
                    <td>{{ branch.country }}</td>
                    <td>{{ branch.region }}</td>
                    <td>{{ branch.city }}</td>
                    <td>{{ branch.phone_number }}</td>
                    {% if branch.is_active %}
                    	<td><span class="label label-success label-bordered">{{ branch.is_active }}</span></td>
                    {% else %}
	                	<td><span class="label label-danger label-bordered">{{ branch.is_active }}</span></td>
                	{% endif %}
                    <td>
                        <a class="btn btn-default btn-icon" href="{% url 'branch:branch_detail' branch.pk %}"><span class="icon-document"></span></a>
                        {% if user.is_manager %}
	                        <a class="btn btn-danger btn-icon btn-clean" href="{% url 'branch:delete_branch' branch.pk %}"><span class="icon-trash3"></span></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}                                                                       
            </tbody>
        </table>
    </div>
</div>
<!-- END DEPOSITS -->


{% endblock %}

branch/templates/branch/update_form.html
{% extends 'base_generic.html' %}

{% load static %}
{% load i18n %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
	<div class="block block-condensed">
	    <div class="app-heading app-heading-small">                                        
	        <div class="title">
	            <h2>Update Branch</h2>
	            <p>Handles the modification of existing branch.</p>
	        </div>
	    </div>
	    <div class="block-content">
		    <form action="{% url 'branch:edit_branch' object.pk %}" method='POST' role='form' class="form" enctype="multipart/form-data" {% if layout != 'vertical' %}class="form-{{ layout }}"{% endif %}>
				{% csrf_token %}
				{% bootstrap_form form %}
				{% bootstrap_form_errors form %}
		        <input type="submit" name="submit" value="Submit" class="btn btn-primary btn-clean btn-lg btn-rounded">
			</form>
	    </div>
	</div>
	{% include 'scripts_base.html' %}
	
{% endblock %}