branch/urls.py
from django.urls import path
from . import views
from . views import (BranchCreateView, BranchDetailView,
                     BranchEditView, BranchListView)

app_name = 'branch'

urlpatterns = [
    path('branch/', BranchListView.as_view(), name='branch_list'),
    path('branch/create/', BranchCreateView.as_view(), name='create_branch'),
    path('branch/detail/<int:pk>/',
         BranchDetailView.as_view(), name='branch_detail'),
    path('branch/edit/<int:pk>/',
         BranchEditView.as_view(), name='edit_branch'),
    path('branch/inactive/<int:pk>/',
         views.delete_branch, name='delete_branch'),
]

clients/urls.py
from django.urls import path
from . import views
from . views import (ClientListView, ClientCreateView,
                     ClientEditView, ClientDetailView)

app_name = 'clients'
urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/new/',
         ClientCreateView.as_view(), name='create_client'),
    path('clients/update/<int:pk>/',
         ClientEditView.as_view(), name='edit_client'),
    path('clients/detail/<int:pk>/',
         ClientDetailView.as_view(), name='client_detail'),
    path('clients/inactive/<int:pk>/',
         views.delete_client, name='delete_client'),
    # path('clients/permanent/delete/<int:pk>/',
    #      views.permanent_delete, name='permanent_delete'),
    path('deposits/', views.deposit_view, name='deposits'),
    path('withdrawals', views.withdrawal_view, name='withdrawals'),
    path('transaction_view/', views.transaction_view, name='transaction_view'),
    path('deposit/receipt/<int:pk>/', views.print_client_deposit,
         name='print_client_deposit'),
    path('withdrawal/receipt/<int:pk>/', views.print_client_withdrawal,
         name='print_client_withdrawal'),
]

dashboard/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . views import HomeView
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('create/user/', views.signupview, name='signup'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/user/', views.user_profile, name='user_profile'),
    path('change/password/user/', views.change_password, name='change_password'),
]

mboapa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, re_path
#from django.conf.urls import url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dashboard.urls')),
    path('branch/', include('branch.urls')),
    path('clients/', include('clients.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>MBOA PA FIANANCIAL SERVICE</title>
        
        <!-- META SECTION -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="shortcut icon" href="{% static 'img/bankLOG.png' %}" type="image/x-icon">
        <link rel="icon" href="{% static 'img/bankLOG.png' %}" type="image/x-icon">
        <!-- END META SECTION -->
        <!-- CSS INCLUDE -->        
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <!-- EOF CSS INCLUDE -->
        {% block static_css %}{% endblock %}
    </head>
    <body>        
        
        <!-- APP WRAPPER -->
        <div class="app">           

            <!-- START APP CONTAINER -->
            <div class="app-container">
                <!-- START SIDEBAR -->
                {% block sidebar %}
                <div class="app-sidebar app-navigation app-navigation-style-default app-navigation-open-hover dir-left" data-type="close-other">
                    <a href="/" class="app-navigation-logo">
                        Mboa Pa - Financial Service 
                    </a>
                    <nav>
                        <ul>
                            <li class="title">MAIN</li>
                            <li><a href="/"><span class="icon-home5"></span> Dashboard</a></li>
                            <li><a href="{% url 'clients:transaction_view' %}"><span class="icon-bag-dollar"></span> Transactions</a></li>
                            <li><a href="{% url 'branch:branch_list' %}"><span class="icon-apartment"></span> Branch</a></li>
                            <li><a href="{% url 'clients:client_list' %}"><span class="icon-users-plus"></span>Clients</a></li>
                            {% if user.is_manager %}               
                            <li><a href="{% url 'dashboard:signup' %}"><span class="icon-user-plus"></span> Add New User</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                {% endblock sidebar %}
                <!-- END SIDEBAR -->
                
                <!-- START APP CONTENT -->
                <div class="app-content app-sidebar-left">
                    <!-- START APP HEADER -->
                    {% block user_content %}
                    <div class="app-header">
                        <ul class="app-header-buttons">
                            <li class="visible-mobile"><a href="#" class="btn btn-link btn-icon" data-sidebar-toggle=".app-sidebar.dir-left"><span class="icon-menu"></span></a></li>
                            <li class="hidden-mobile"><a href="#" class="btn btn-link btn-icon" data-sidebar-minimize=".app-sidebar.dir-left"><span class="icon-list4"></span></a></li>
                        </ul>
                        <!-- <form class="app-header-search" action="" method="post">        
                            <input type="text" name="keyword" placeholder="Search">
                        </form>  -->   
                    
                        <ul class="app-header-buttons pull-right">
                            <li>
                                {% if user.is_authenticated %}
                                <div class="contact contact-rounded contact-bordered contact-lg contact-ps-controls">
                                    {% if user.profile_pic %}
                                        <img src="{{ user.profile_pic.url }}" alt="{{ user.username }}" width="300px" height="40px">
                                    {% else %}
                                        <img src="{% static 'img/user/no-image.png' %}" alt="{{ user.username }}">
                                    {% endif %}
                                    <div class="contact-container">
                                        <a href="{% url 'dashboard:user_profile' %}">{{ user.username }}</a>
                                        <span>{{ user.email }}</span>
                                    </div>
                                    <div class="contact-controls">
                                        <div class="dropdown">
                                            <button type="button" class="btn btn-default btn-icon" data-toggle="dropdown"><span class="icon-cog"></span></button>                        
                                            <ul class="dropdown-menu dropdown-left">
                                                <li><a href="{% url 'dashboard:change_password' %}"><span class="icon-cog"></span> Manage Password</a></li> 
                                                <li class="divider"></li>
                                                <li><a href="{% url 'dashboard:logout' %}"><span class="icon-exit-right"></span> Log Out</a></li> 
                                            </ul>
                                        </div>                    
                                    </div>
                                </div>
                                {% endif %}
                            </li>        
                        </ul>
                    </div>
                    {% endblock user_content %}
                    <!-- END APP HEADER  -->
                    
                    <!-- START PAGE HEADING -->
                    <div class="app-heading app-heading-bordered app-heading-page">
                        <div class="icon icon-lg">
                            <span class="icon-laptop-phone"></span>
                        </div>
                        <div class="title">
                            <h1>Mboa Pa - Fianancial Service</h1>
                            <p>Microfinance system administration</p>
                        </div>               
                        <!--<div class="heading-elements">
                            <a href="#" class="btn btn-danger" id="page-like"><span class="app-spinner loading"></span> loading...</a>
                        </div>-->
                    </div>
                    <div class="app-heading-container app-heading-bordered bottom">
                        <ul class="breadcrumb">
                            <li><a href="/">Home</a></li>                                                     
                            <li class="active">Dashboard</li>
                        </ul>
                    </div>
                    <!-- END PAGE HEADING -->
                    
                    {% block content %}
                    {% if messages %}
						<div class="messages">
							<ul>
							{% for message in messages %}
								<li class="{{ message.tag }}alert alert-success alert-dismissable">
									{{ message }}
								</li>
							{% endfor %}
							</ul>
						</div>
					{% endif %}

                    {% endblock %}
                    
                </div>
                <!-- END APP CONTENT -->
                                
            </div>
            <!-- END APP CONTAINER -->
    {% block footer %}
    	<!-- START APP FOOTER -->
        <div class="app-footer app-footer-default" id="footer">
        
            <div class="alert alert-primary alert-dismissible alert-inside text-center">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span class="icon-cross"></span></button>
                We use cookies to offer you the best experience on our website. Continuing browsing, you accept our cookies policy.
            </div>
            <div class="app-footer-line darken">                
                <div class="copyright wide text-center">&copy; {% now 'Y' %} Mboa Pa Fianancial Services. All right reserved.</div>                
            </div>
        </div>
        <!-- END APP FOOTER -->
    {% endblock %}

  {% include 'scripts_base.html' %}
  {% block script_js %}{% endblock %}

templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>                        
        <title>MBOA PA FIANANCIAL SERVICE</title>            
        
        <!-- META SECTION -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="shortcut icon" href="{% static 'img/bankLOG.png' %}" type="image/x-icon">
        <link rel="icon" href="{% static 'img/bankLOG.png' %}" type="image/x-icon">
        {% load bootstrap3 %}

		{% bootstrap_css %}
		{% bootstrap_javascript %}
        <!-- END META SECTION -->
        <!-- CSS INCLUDE -->        
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <!-- EOF CSS INCLUDE -->
        {% block static_css %}{% endblock %}
    </head>
    <body>        
        
        <!-- APP WRAPPER -->
        <div class="app">                       
            
            <!-- START APP CONTAINER -->
            <div class="app-container">                
                <!-- START APP HEADER -->
                {% block top_nav %}
                <div class="app-header">
                    <div class="container container-boxed">
                        <ul class="app-header-buttons visible-mobile">
                            <li><a href="/" class="btn btn-link btn-icon" data-navigation-horizontal-toggle="true"><span class="icon-menu"></span></a></li>                    
                        </ul>
                        <a href="/" class="app-header-logo app-header-logo-light app-header-logo-condensed">home</a>
                
                        <ul class="app-header-buttons pull-right">
                            <li>
                                {% if user.is_authenticated %}
                                <div class="contact contact-rounded contact-bordered contact-lg contact-ps-controls">
                                    {% if user.profile_pic %}
                                        <img src="{{ user.profile_pic.url }}" alt="{{ user.username }}" width="300px" height="40px">
                                    {% else %}
                                        <img src="{% static 'img/user/no-image.png' %}" alt="{{ user.username }}">
                                    {% endif %}
                                    <div class="contact-container">
                                        <a href="{% url 'dashboard:user_profile' %}">{{ user.username }}</a>
                                        <span>{{ user.email }}</span>
                                    </div>
                                    <div class="contact-controls">
                                        <div class="dropdown">
                                            <button type="button" class="btn btn-default btn-icon" data-toggle="dropdown"><span class="icon-cog"></span></button>                        
                                            <ul class="dropdown-menu dropdown-left">
                                                <li><a href="{% url 'dashboard:change_password' %}"><span class="icon-cog"></span> Manage Password</a></li> 
                                                <li class="divider"></li>
                                                <li><a href="{% url 'dashboard:logout' %}"><span class="icon-exit-right"></span> Log Out</a></li> 
                                            </ul>
                                        </div>                    
                                    </div>
                                </div>
                                {% endif %}
                            </li>    
                        </ul>
                    </div>
                </div>
                {% endblock %}
                <!-- END APP HEADER  -->
                
                <!-- START APP CONTENT -->
                <div class="app-content">
                	{% block bottom_nav %}
                    <div class="app-navigation-horizontal margin-bottom-15">    
                        <div class="container container-boxed">
                            <nav>
                                <ul>
                                    <li>
                                        <a href="#"><span class="icon-earth"></span> My Clients</a>
                                        <ul>
                                        	<li><a href="{% url 'clients:client_list' %}">Clients</a></li>
                                            <li><a href="{% url 'clients:transaction_view' %}">Transactions</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#"><span class="icon-sync"></span> Branch</a>
                                        <ul>
                                            <li><a href="{% url 'branch:branch_list' %}">All Branch</a></li>
                                            <li><a href="{% url 'branch:create_branch' %}">Create Branch</a></li>
                                        </ul>
                                    </li>
                                    <!-- <li>
                                        <a href="#"><span class="icon-cog"></span> Settings</a>
                                        <ul>
                                            <li><a href="pages-bank-settings.html">Account</a></li>
                                            <li><a href="pages-bank-security.html">Security</a></li>                                                
                                        </ul>
                                    </li>  -->               
                                </ul>
                            </nav>
                        </div>
                    </div>
                    {% endblock %}
                                                                                                  
                    <!-- START PAGE CONTAINER -->
                    <div class="container container-boxed">
                    	{% if messages %}
							<div class="messages">
								<ul>
								{% for message in messages %}
									<li class="{{ message.tag }}alert alert-success alert-dismissable">
										{{ message }}
									</li>
								{% endfor %}
								</ul>
							</div>
						{% endif %}
                        
                        {% block content %}

                        {% endblock %}
                        
                    </div>
                    <!-- END PAGE CONTAINER -->
                    
                </div>
                <!-- END APP CONTENT -->
                                
            </div>
            <!-- END APP CONTAINER -->            
            
            <!-- START APP FOOTER -->
            <div class="app-footer app-footer-default" id="footer">
                
                <div class="container container-boxed">
                    <div class="app-footer-line">
                        <div class="copyright">&copy; {% now 'Y' %} Mboa Pa Fianancial Services. All right reserved.</div>
                        <div class="pull-right">
                            <ul class="list-inline">
                                <li><a href="#">About</a></li>
                                <li><a href="#">Help</a></li>
                                <li><a href="#">API</a></li>
                                <li><a href="#">Contacts</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
            </div>
            <!-- END APP FOOTER -->
        </div>        
        <!-- END APP WRAPPER -->                
        
        {% include 'scripts_base.html' %}
        {% block script_js %}{% endblock %}
        <!-- END SCRIPTS -->
    </body>
</html>

templates/scripts_base.html
{% load static %}
<script type="text/javascript" src="{% static 'js/vendor/jquery/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/jquery/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/bootstrap/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/moment/moment.min.js' %}"></script>       

<script type="text/javascript" src="{% static 'js/vendor/customscrollbar/jquery.mCustomScrollbar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/bootstrap-select/bootstrap-select.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/maskedinput/jquery.maskedinput.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/form-validator/jquery.form-validator.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/noty/jquery.noty.packaged.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/datatables/dataTables.bootstrap.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/sweetalert/sweetalert.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/knob/jquery.knob.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/jvectormap/jquery-jvectormap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/jvectormap/jquery-jvectormap-us-aea-en.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/sparkline/jquery.sparkline.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/morris/raphael.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/morris/morris.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/rickshaw/d3.v3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/rickshaw/rickshaw.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/vendor/isotope/isotope.pkgd.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/app.js' %}"></script>
<script type="text/javascript" src="{% static 'js/app_plugins.js' %}"></script>
<script type="text/javascript" src="{% static 'js/app_demo.js' %}"></script>
<!-- END SCRIPTS -->
<script type="text/javascript" src="{% static 'js/app_demo_dashboard.js' %}"></script>